---
title: "Final Project"
author: "Arwen Lyons"
date: "2024-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


(Visualizations should have informative labels and names and have a small number of digits presented, using kable or modelssummary to nicley format)

extra point for:
- merging two different data sets
- additional analysis for possible confounders or alternative explinations (that poor economics mostly harm the incombent party)
## Introduction 

Research Question:
- hypothesis
- why this is interesting

## Data Section 
- breifly describes data source, 
- how key dependent and independent variables are measured
    - (eg survey, statistical model, or expert coding) 
- is this a cross sectional or differences in differences 
    
# Plot that summarizes the dependent variable 
  - so this is going to be my plot of unemployment rates for election years
  
  
## Results Section
  - this is going to have my four graphs of the elections results and maybe my oink graph if I can fix it
  - output for the main regression of interest
      - p value
  - interpret the main coefficient of interest in uyour regression 
  - comment the statistical significance of the estimated coefficient and whether or not you believe the coefficient to represent a causal effect 
      
## Conclusion 
  - summarizes results 
  - extent to which you find support for your hypotheis
  - limitations in data/how data could be improved
      - weak P value relationship, to properly do this experiment would need unployment data for all of these coutnies 
  - confounding factors
  

- lecture notes back to observational studies
  - before and after treatment control 

This is a tough relationship to analyze because there are a lot of economic factors that influence unemployment rate and presidential approval, for example Obama was elected in 2008 in part because he offered solutions to the 2008 economic recession and housing crisis which had resulted in higher unemployment rates. Obama was reelected in 2012 despite higher unemployment rates than when he entered office this would seem to go against my hypothesis, that republicans are more likely to be elected when there are low unemployment rates because voters associate that with a bad economy and traditionally trust republicans more with the economy. In 2016 where unemployment rates were significantly lower nearly 5% less than when Obama took office in 2012, Trump was elected by much stronger MOV's than Obama in 2012 (although slightly less than in 2008). This again seems to disprove my hypothesis as the low unemployment rates seemed to benefit the republican candidate (Trump). However rather than proving the opposite of my hypothesis comparing these two graphs seems to support a different hypothesis that there may not be a strong relationship between unemployment rates and party victory. The unemployment data for 2020 is clearly skewed as a result of Covid resulting in a huge spike in 2020 Trump oversaw this spike while in office and was superseded by Biden. Maybe a similarity can be drawn between a large spike in unemployment, 2008, and 2020, and the country turning to a Democratic Candidate. 





















































